server.port=8080

# ===============================
# = DATA SOURCE - MySQL
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/restaurante?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=dangelo26
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# = JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# ===============================
# = JWT Configuration
# ===============================
application.security.jwt.secret-key=EstaEsUnaClaveMuySecretaYSeguraParaMiRestaurante12345ParaGenerarTokensJWT
application.security.jwt.access-token-expiration=3600000
application.security.jwt.refresh-token-expiration=604800000

spring.application.name=backend
